baseURL: "https://okx.joinhelpers.com/"
languageCode: "ko-kr"
title: "OKX 가이드 (2025 최신) | JoinHelpers"
theme: "PaperMod"

params:
  defaultTheme: auto
  ShowReadingTime: false
  ShowCodeCopyButtons: true
  description: "OKX 가입·이용·추천인 변경(리셋)까지 한 번에 끝내는 2025 최신 공식 가이드"
  author: "JoinHelpers"
  env: production
  ShowBreadCrumbs: true
  ShowPostNavLinks: true

outputs:
  home: [HTML, RSS, JSON]

enableRobotsTXT: true
sitemap:
  changefreq: daily
  priority: 0.7
  filename: sitemap.xml

mainSections: []

markup:
  goldmark:
    renderer:
      unsafe: true
